In [19]:
from bs4 import BeautifulSoup as bs
from splinter import Browser
import pandas as pd
from requests import get
import itertools
import matplotlib.pyplot as plt
from time import sleep
from random import randint

In [20]:
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [21]:
url = 'https://www.mbofstockton.com/used-vehicles/'
browser.visit(url)

In [22]:
html=browser.html

In [23]:
stockton_soup = bs(html, 'html.parser')

In [255]:
# stockton_soup.find_all('div',class_="options")

In [256]:


mylist=[]
options=stockton_soup.find_all('div',class_='options')
for car in options:
#     car_sublist = []
    mydict={}
    for li in car.find_all('li'):
        
        mydict[li.text.split(':')[0]]=li.text.split(':')[1]
        details=car.text
#         print(details, '-'*80)
    mylist.append(mydict)

In [257]:
mylist2=[{k.replace('\n','').replace('\t',''): v.replace('\n','').replace('\t','') for k,v in x.items()} for x in mylist]

In [28]:
options_df=pd.DataFrame(mylist2)
options_df

,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,RWD,Gas V6 2.5L/152,Charcoal,32 MPG ...,NaN,"157,858",6-Speed Automatic
1,RWD,Gas V6 3.2L/195,Capri Blue Metallic,28 MPG ...,NaN,"74,456",5-Speed Automatic w/OD
2,4WD,Gas/Ethanol V8 5.3L/325,Tungsten Metallic,22 MPG ...,Jet Black,"172,207",6-Speed Automatic
3,FWD,Regular Unleaded I-4 1.6 L/97,Chalk White,36 MPG ...,Beige,"24,026",6-Speed Automatic w/OD
4,RWD,Turbocharged Gas I4 1.8L/110,Arctic White,31 MPG ...,Almond MB-Tex,"136,268",7-Speed Automatic
5,FWD,Regular Unleaded I-4 1.8 L/110,Super Black,37 MPG ...,Charcoal,"23,821",1-Speed CVT w/OD
6,FWD,Regular Unleaded I-4 2.0 L/122,Silver,38 MPG ...,Black,"33,316",6-Speed Auto-Shift Manual w/OD
7,4WD,Gas V8 4.4L/268,White,18 MPG ...,NaN,"74,803",6-Speed Automatic w/OD
8,FWD,Regular Unleaded I-4 1.6 L/97,Century White,36 MPG ...,Black,"26,898",6-Speed Auto-Shift Manual w/OD
9,RWD,Turbocharged I4 2.0L/122,Thunder Gray ChromaFlair,31 MPG ...,Light Platinum w/Jet Black Accents,"89,244",6-Speed Automatic
10,FWD,Regular Unleaded I-4 2.4 L/144,Crystal Black Pearl,36 MPG ...,NaN,"74,636",1-Speed CVT w/OD
11,FWD,Regular Unleaded I-4 1.8 L/110,Super White,36 MPG ...,Ash,"38,364",1-Speed CVT w/OD
12,4WD,Regular Unleaded V-6 3.5 L/213,NaN,23 MPG ...,NaN,"137,431",6-Speed Automatic w/OD
13,FWD,Gas/Electric I-4 2.0 L/122,Oxford White,41 MPG ...,Ebony,"33,558",1-Speed CVT w/OD
14,FWD,Regular Unleaded I-4 2.5 L/152,Brilliant Silver,38 MPG ...,Charcoal,"22,025",1-Speed CVT w/OD
15,AWD,Regular Unleaded I-4 2.0 L/122,Magnetic Black,30 MPG ...,Charcoal,"24,991",1-Speed CVT w/OD
16,AWD,Regular Unleaded I-4 2.5 L/152,Brilliant Silver,32 MPG ...,Charcoal,"36,398",1-Speed CVT w/OD
17,4WD,Regular Unleaded V-6 3.5 L/213,White,23 MPG ...,NaN,"103,135",6-Speed Automatic w/OD
18,RWD,Regular Unleaded V-6 3.6 L/220,Granite Pearlcoat,30 MPG ...,Black,"27,961",8-Speed Automatic w/OD
19,RWD,Regular Unleaded V-6 3.6 L/220,Gloss Black,30 MPG ...,Black,"38,623",8-Speed Automatic w/OD

In [29]:
first_car=stockton_soup.find('div',class_='vehicle-overview')

In [30]:
vin_num=first_car.span.text
vin_num.split(':')[1]

' JTHBK262X75028035'

In [31]:
org_first_car_price=first_car.find('div',class_='price-block our-price real-price')
org_first_car_price.find('span',class_='price').text

'$8,900'

In [32]:
stock=first_car.find('span',class_='stock-label').text
stock=stock.split(':')[1]
stock

' P3392A'

In [33]:
headers = {"Accept-Language": "en-US, en;q=0.5"}
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import pandas as pd
from urllib.request import urlopen
prices=[]
vins=[]
stocks=[]
titles=[]
start_time = time()
requests = 0
pages = [str(i) for i in range(1,5)]

for page in pages:
    
#     response = get(f'https://www.mbofstockton.com/used-vehicles/#action=im_ajax_call&perform=get_results&page={page}',headers = headers)
    
    response = get(f'https://www.mbofstockton.com/used-vehicles/#action=im_ajax_call&perform=get_results&page=2',headers = headers)
    
    
    sleep(randint(8,15))
    requests += 1
    elapsed_time = time() - start_time
    print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
#     clear_output(wait = True)
     
    if response.status_code != 200:
        warn('Request: {}; Status code: {}'.format(requests, response.status_code))
    if requests > 72:
        warn('Number of requests was greater than expected.')
        break
    stockton_soup = bs(response.text, 'html.parser')
    print(response.text)
    cars=stockton_soup.find_all('div',class_='vehicle-overview')

    for car in cars:
        stock=car.find('span',class_='stock-label').text
        stock=stock.split(':')[1]
        stocks.append(stock)

        vin=car.span.text
        vin=vin.split(':')[1]
        vins.append(vin)

        price=car.find('div',class_='price-block our-price real-price').find('span',class_='price').text
        prices.append(price)
        prices=[x.replace('\n','').replace('\t','') for x in prices]
        
        title=car.find('a').text
        titles.append(title)

NameError: name 'time' is not defined

In [ ]:
titles

In [ ]:
browser.click_link_by_text

In [ ]:
titles

In [ ]:
stockton_df=pd.DataFrame({'Stock #': stocks,
'Original Price': prices,
'Vin #': vins,
})
stockton_df

In [ ]:
pd.merge(stockton_df,options_df,left_index=True,right_index=True)

In [203]:
import codecs
f=codecs.open("Stockton_website_1.html", 'r','utf-8').read()
# print (f.read())

In [204]:
stockton_soup_1= bs(f,'html.parser')

In [205]:
mylist=[]
options=stockton_soup_1.find_all('div',class_='options')
for car in options:
#     car_sublist = []
    mydict={}
    for li in car.find_all('li'):
        
        mydict[li.text.split(':')[0]]=li.text.split(':')[1]
        details=car.text
#         print(details, '-'*80)
    mylist.append(mydict)

In [206]:
mylist2=[{k.replace('\n','').replace('\t',''): v.replace('\n','').replace('\t','') for k,v in x.items()} for x in mylist]

In [207]:
options_df=pd.DataFrame(mylist2)
options_df.head()

,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,RWD,Gas V6 2.5L/152,Charcoal,32 MPG ...,NaN,"157,858",6-Speed Automatic
1,RWD,Gas V6 3.2L/195,Capri Blue Metallic,28 MPG ...,NaN,"74,456",5-Speed Automatic w/OD
2,FWD,Regular Unleaded I-4 1.6 L/97,Chalk White,36 MPG ...,Beige,"24,026",6-Speed Automatic w/OD
3,RWD,Turbocharged Gas I4 1.8L/110,Arctic White,31 MPG ...,Almond MB-Tex,"136,268",7-Speed Automatic
4,FWD,Regular Unleaded I-4 1.8 L/110,Super Black,37 MPG ...,Charcoal,"23,821",1-Speed CVT w/OD

In [208]:
cars=stockton_soup_1.find_all('div',class_='vehicle-overview')

In [210]:
stocks=[]
prices=[]
vins=[]
sale_prices=[]
titles=[]
years=[]

cars=stockton_soup.find_all('div',class_='vehicle-overview')

for car in cars:
    stock=car.find('span',class_='stock-label').text
    stock=stock.split(':')[1]
    stocks.append(stock)

    vin=car.span.text
    vin=vin.split(':')[1]
    vins.append(vin)

    price=car.find('div',class_='price-block our-price real-price').find('span',class_='price').text
    prices.append(price)
    prices=[x.replace('\n','').replace('\t','') for x in prices]
        
    year=car.find('a').text
    if year.split(" ")[0] == "Certified":
        year=year.split(" ")[2]
        years.append(year)
    else:
        year=year.split(" ")[1]
        years.append(year)
        
    title=car.find('a').text
    if title.split(' ',2)[0]=='Pre-Owned':
        title=title.split(' ',2)[2]
        titles.append(title)
    else:
        title=title.split(' ',3)[3]
        titles.append(title)

In [211]:
stockton_df_1=pd.DataFrame({'Stock #': stocks,
'Original Price': prices,
'Vin #': vins,
'Vehicle Name':titles,
'Year':years
})
stockton_df_1

,Stock #,Original Price,Vin #,Vehicle Name,Year
0,P3392A,"$8,900",JTHBK262X75028035,Lexus IS 250 250,2007
1,L5328A,"$9,999",WDBUF65J85A693548,Mercedes-Benz E-Class 3.2L,2005
2,P3423A,"$11,040",1GCVKREC5EZ410142,Chevrolet Silverado 1500 LT 4WD,2014
3,P3440,"$11,988",KMHCT4AE5HU362511,Hyundai Accent SE,2017
4,P3349A,"$11,995",WDDGF4HB6CA728789,Mercedes-Benz C 250 With Navigation,2012
5,P3410,"$12,988",3N1AB7AP2HL710117,Nissan Sentra SV,2017
6,P3420,"$12,988",1FADP3K26JL324170,Ford Focus SE,2018
7,5793A,"$12,995",SALSF25469A213372,Land Rover Range Rover Sport HSE With Navigati...,2009
8,P3289,"$13,488",KMHTC6AD2GU257832,Hyundai Veloster,2016
9,P3276A,"$13,988",1G6AE5SXXD0137372,Cadillac ATS Premium With Navigation,2013
10,P3391A,"$14,040",1HGCR2F80FA156555,Honda Accord Sedan EX-L,2015
11,P3437,"$14,788",2T1BURHE6JC989284,Toyota Corolla LE,2018
12,5759A,"$14,988",1FM5K8F84EGA13808,Ford Explorer Limited 4WD,2014
13,P3429,"$14,988",3FA6P0LU8HR232707,Ford Fusion Hybrid SE,2017
14,p3441,"$15,988",1N4AL3AP7JC111627,Nissan Altima 2.5 SV,2018
15,P3404,"$17,988",JN1BJ1CR5JW264130,Nissan Rogue Sport S AWD,2018
16,P3436,"$17,988",KNMAT2MV7JP568882,Nissan Rogue SV AWD,2018
17,5821A,"$18,999",1FM5K8F88EGC13235,Ford Explorer Limited 4WD,2014
18,P3398,"$21,988",2C3CDZAG1JH237647,Dodge Challenger SXT,2018
19,P3444A,"$21,999",2C3CCABGXHH612593,Chrysler 300 300S,2017

In [212]:
stockton_df_1=pd.merge(stockton_df_1,options_df,left_index=True,right_index=True)
stockton_df_1.head()

,Stock #,Original Price,Vin #,Vehicle Name,Year,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,P3392A,"$8,900",JTHBK262X75028035,Lexus IS 250 250,2007,RWD,Gas V6 2.5L/152,Charcoal,32 MPG ...,NaN,"157,858",6-Speed Automatic
1,L5328A,"$9,999",WDBUF65J85A693548,Mercedes-Benz E-Class 3.2L,2005,RWD,Gas V6 3.2L/195,Capri Blue Metallic,28 MPG ...,NaN,"74,456",5-Speed Automatic w/OD
2,P3423A,"$11,040",1GCVKREC5EZ410142,Chevrolet Silverado 1500 LT 4WD,2014,FWD,Regular Unleaded I-4 1.6 L/97,Chalk White,36 MPG ...,Beige,"24,026",6-Speed Automatic w/OD
3,P3440,"$11,988",KMHCT4AE5HU362511,Hyundai Accent SE,2017,RWD,Turbocharged Gas I4 1.8L/110,Arctic White,31 MPG ...,Almond MB-Tex,"136,268",7-Speed Automatic
4,P3349A,"$11,995",WDDGF4HB6CA728789,Mercedes-Benz C 250 With Navigation,2012,FWD,Regular Unleaded I-4 1.8 L/110,Super Black,37 MPG ...,Charcoal,"23,821",1-Speed CVT w/OD

In [232]:
import codecs
f=codecs.open("Stockton_website_2.html", 'r','utf-8').read()
# print (f.read())

In [233]:
stockton_soup_2 = bs(f,'html.parser')

In [234]:
mylist=[]
options=stockton_soup_2.find_all('div',class_='options')
for car in options:
#     car_sublist = []
    mydict={}
    for li in car.find_all('li'):
        
        mydict[li.text.split(':')[0]]=li.text.split(':')[1]
        details=car.text
#         print(details, '-'*80)
    mylist.append(mydict)

In [235]:
mylist2=[{k.replace('\n','').replace('\t',''): v.replace('\n','').replace('\t','') for k,v in x.items()} for x in mylist]

In [236]:
options_df=pd.DataFrame(mylist2)
options_df.head()

,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,FWD,Regular Unleaded I-4 2.5 L/152,Sonic Silver Metallic,31 MPG ...,Black,"33,748",6-Speed Automatic w/OD
1,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Cirrus White,32 MPG ...,Beige MB-Tex,"48,200",7-Speed Auto-Shift Manual w/OD
2,4WD,Regular Unleaded V-6 3.2 L/198,Granite Crystal Metallic Clearcoat,27 MPG ...,Black,"28,221",9-Speed Automatic w/OD
3,4WD,Regular Unleaded I-4 2.4 L/144,Bright White Clearcoat,25 MPG ...,Black,"34,195",9-Speed Automatic w/OD
4,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Cirrus White,31 MPG ...,Black MB-Tex,"31,502",7-Speed Auto-Shift Manual w/OD

In [237]:
cars=stockton_soup_2.find_all('div',class_='vehicle-overview')

In [238]:
stocks=[]
prices=[]
vins=[]
sale_prices=[]
titles=[]
years=[]

for car in cars:
    stock=car.find('span',class_='stock-label').text
    stock=stock.split(':')[1]
    stocks.append(stock)

    vin=car.span.text
    vin=vin.split(':')[1]
    vins.append(vin)

    price=car.find('div',class_='price-block our-price real-price').find('span',class_='price').text
    prices.append(price)
    prices=[x.replace('\n','').replace('\t','') for x in prices]
        
    year=car.find('a').text
    if year.split(" ")[0] == "Certified":
        year=year.split(" ")[2]
        years.append(year)
    else:
        year=year.split(" ")[1]
        years.append(year)
        
    title=car.find('a').text
    if title.split(' ',2)[0]=='Pre-Owned':
        title=title.split(' ',2)[2]
        titles.append(title)
    else:
        title=title.split(' ',3)[3]
        titles.append(title)

In [239]:
stockton_df_2=pd.DataFrame({'Stock #': stocks,
'Original Price': prices,
'Vin #': vins,
'Vehicle Name':titles,
'Year':years
})
stockton_df_2

,Stock #,Original Price,Vin #,Vehicle Name,Year
0,P3430,"$23,988",JM3KFADM2J0325641,Mazda CX-5 Grand Touring With Navigation,2018
1,P3342,"$23,988",WDCTG4GB2GJ192298,Mercedes-Benz GLA 250 AWD 4MATIC®,2016
2,P3409,"$24,988",1C4PJMDX0KD216632,Jeep Cherokee Limited 4WD,2019
3,P3457,"$24,988",1C4PJMBBXJD569174,Jeep Cherokee Trailhawk 4WD,2018
4,P3428,"$25,988",WDCTG4GB7HJ323842,Mercedes-Benz GLA 250 AWD 4MATIC®,2017
5,P3425,"$25,988",1C4PJMBX9KD313718,Jeep Cherokee Trailhawk 4WD,2019
6,P3445,"$25,999",2G61M5S35J9158499,Cadillac XTS Luxury,2018
7,P3499A,"$26,988",1FA6P8CF0G5336884,Ford Mustang GT,2016
8,5854a,"$26,988",JM3KFBDL2H0106122,Mazda CX-5 Grand Touring With Navigation & AWD,2017
9,P3431,"$27,988",5N1DR2MM7JC611400,Nissan Pathfinder SL 4WD,2018
10,P3456,"$27,999",1C4PJMDX3KD346775,Jeep Cherokee Limited 4WD,2019
11,P3382,"$28,988",1C6RR7TTXKS510818,Ram 1500 Classic SLT 4WD,2019
12,P3435,"$28,988",1C4HJWDGXHL754270,Jeep Wrangler Unlimited Sport 4WD,2017
13,P3424,"$29,988",4JGDA5GB3FA578658,Mercedes-Benz M-Class ML 400 AWD 4MATIC®,2015
14,P3375,"$29,999",WDC0G4KBXGF007976,Mercedes-Benz GLC 300 AWD 4MATIC®,2016
15,P3413,"$30,988",1C4HJWEG7HL754239,Jeep Wrangler Unlimited Sahara 4WD,2017
16,P3453,"$31,988",1FTEW1EB9JKE47985,Ford F-150 XLT 4WD,2018
17,P3359,"$31,988",WDC0G4KB8GF024999,Mercedes-Benz GLC 300 AWD 4MATIC®,2016
18,P3432,"$31,988",4JGDA5HBXGA770224,Mercedes-Benz GLE 350 AWD 4MATIC®,2016
19,P3386,"$31,999",1C4RDJDG5KC559778,Dodge Durango GT Plus AWD,2019

In [240]:
stockton_df_2=pd.merge(stockton_df_2,options_df,left_index=True,right_index=True)
stockton_df_2

,Stock #,Original Price,Vin #,Vehicle Name,Year,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,P3430,"$23,988",JM3KFADM2J0325641,Mazda CX-5 Grand Touring With Navigation,2018,FWD,Regular Unleaded I-4 2.5 L/152,Sonic Silver Metallic,31 MPG ...,Black,"33,748",6-Speed Automatic w/OD
1,P3342,"$23,988",WDCTG4GB2GJ192298,Mercedes-Benz GLA 250 AWD 4MATIC®,2016,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Cirrus White,32 MPG ...,Beige MB-Tex,"48,200",7-Speed Auto-Shift Manual w/OD
2,P3409,"$24,988",1C4PJMDX0KD216632,Jeep Cherokee Limited 4WD,2019,4WD,Regular Unleaded V-6 3.2 L/198,Granite Crystal Metallic Clearcoat,27 MPG ...,Black,"28,221",9-Speed Automatic w/OD
3,P3457,"$24,988",1C4PJMBBXJD569174,Jeep Cherokee Trailhawk 4WD,2018,4WD,Regular Unleaded I-4 2.4 L/144,Bright White Clearcoat,25 MPG ...,Black,"34,195",9-Speed Automatic w/OD
4,P3428,"$25,988",WDCTG4GB7HJ323842,Mercedes-Benz GLA 250 AWD 4MATIC®,2017,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Cirrus White,31 MPG ...,Black MB-Tex,"31,502",7-Speed Auto-Shift Manual w/OD
5,P3425,"$25,988",1C4PJMBX9KD313718,Jeep Cherokee Trailhawk 4WD,2019,4WD,Regular Unleaded V-6 3.2 L/198,Diamond Black Crystal Pearlcoat,24 MPG ...,Black,"13,995",9-Speed Automatic w/OD
6,P3445,"$25,999",2G61M5S35J9158499,Cadillac XTS Luxury,2018,FWD,Gas V6 3.6L/217,Stellar Black Metallic,28 MPG ...,Jet Black,"38,611",6-Speed Automatic w/Manual Shift
7,P3499A,"$26,988",1FA6P8CF0G5336884,Ford Mustang GT,2016,RWD,Premium Unleaded V-8 5.0 L/302,Shadow Black,25 MPG ...,Ebony,"27,933",6-Speed Automatic w/OD
8,5854a,"$26,988",JM3KFBDL2H0106122,Mazda CX-5 Grand Touring With Navigation & AWD,2017,AWD,Regular Unleaded I-4 2.5 L/152,Machine Gray Metallic,29 MPG ...,Black,"15,444",6-Speed Automatic w/OD
9,P3431,"$27,988",5N1DR2MM7JC611400,Nissan Pathfinder SL 4WD,2018,4WD,Regular Unleaded V-6 3.5 L/213,Gun Metallic,26 MPG ...,Charcoal,"28,524",1-Speed CVT w/OD
10,P3456,"$27,999",1C4PJMDX3KD346775,Jeep Cherokee Limited 4WD,2019,4WD,Regular Unleaded V-6 3.2 L/198,Bright White Clearcoat,27 MPG ...,Black,"12,587",9-Speed Automatic w/OD
11,P3382,"$28,988",1C6RR7TTXKS510818,Ram 1500 Classic SLT 4WD,2019,4WD,Regular Unleaded V-8 5.7 L/345,Bright White Clearcoat,21 MPG ...,Diesel Gray/Black,"17,249",8-Speed Automatic w/OD
12,P3435,"$28,988",1C4HJWDGXHL754270,Jeep Wrangler Unlimited Sport 4WD,2017,4WD,Regular Unleaded V-6 3.6 L/220,Bright White Clearcoat,20 MPG ...,Black,"41,035",5-Speed Automatic w/OD
13,P3424,"$29,988",4JGDA5GB3FA578658,Mercedes-Benz M-Class ML 400 AWD 4MATIC®,2015,AWD 4MATIC,Twin Turbo Premium Unleaded V-6 3.0 L/183,Black,22 MPG ...,Black Leather,"39,996",7-Speed Automatic w/OD
14,P3375,"$29,999",WDC0G4KBXGF007976,Mercedes-Benz GLC 300 AWD 4MATIC®,2016,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Black,28 MPG ...,Silk Beige MB-Tex,"28,094",9-Speed Automatic w/OD
15,P3413,"$30,988",1C4HJWEG7HL754239,Jeep Wrangler Unlimited Sahara 4WD,2017,4WD,Regular Unleaded V-6 3.6 L/220,Bright White Clearcoat,20 MPG ...,Black,"24,432",5-Speed Automatic w/OD
16,P3453,"$31,988",1FTEW1EB9JKE47985,Ford F-150 XLT 4WD,2018,4WD,Regular Unleaded V-6 3.3 L,NaN,23 MPG ...,NaN,"24,998",6-Speed Automatic w/OD
17,P3359,"$31,988",WDC0G4KB8GF024999,Mercedes-Benz GLC 300 AWD 4MATIC®,2016,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Polar White,28 MPG ...,Silk Beige MB-Tex,"29,540",9-Speed Automatic w/OD
18,P3432,"$31,988",4JGDA5HBXGA770224,Mercedes-Benz GLE 350 AWD 4MATIC®,2016,AWD 4MATIC,Premium Unleaded V-6 3.5 L/213,Black,22 MPG ...,Black MB-Tex,"59,034",7-Speed Automatic w/OD
19,P3386,"$31,999",1C4RDJDG5KC559778,Dodge Durango GT Plus AWD,2019,AWD,Regular Unleaded V-6 3.6 L/220,DB Black Clearcoat,25 MPG ...,Black,"12,860",8-Speed Automatic w/OD

In [241]:
import codecs
f=codecs.open("Stockton_website_3.html", 'r','utf-8').read()
# print (f.read())

In [242]:
stockton_soup_3 = bs(f,'html.parser')

In [243]:
mylist=[]
options=stockton_soup_3.find_all('div',class_='options')
for car in options:
#     car_sublist = []
    mydict={}
    for li in car.find_all('li'):
        
        mydict[li.text.split(':')[0]]=li.text.split(':')[1]
        details=car.text
#         print(details, '-'*80)
    mylist.append(mydict)

In [244]:
mylist2=[{k.replace('\n','').replace('\t',''): v.replace('\n','').replace('\t','') for k,v in x.items()} for x in mylist]

In [245]:
options_df=pd.DataFrame(mylist2)
options_df.head()

,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,4WD,Regular Unleaded V-8 5.7 L/345,Billet Silver Metallic Clearcoat,21 MPG ...,Black,"24,283",8-Speed Automatic w/OD
1,4WD,Twin Turbo Regular Unleaded V-6 3.5 L/213,Ingot Silver Metallic,23 MPG ...,Medium Earth Gray,"18,677",NaN
2,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Polar White,28 MPG ...,Black MB-Tex,"22,395",9-Speed Automatic w/OD
3,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,White,30 MPG ...,NaN,"45,051",9-Speed Automatic w/OD
4,RWD,Premium Unleaded V-6 3.5 L/213,NaN,24 MPG ...,NaN,"27,888",7-Speed Automatic w/OD

In [246]:
cars=stockton_soup_3.find_all('div',class_='vehicle-overview')

In [247]:
stocks=[]
prices=[]
vins=[]
sale_prices=[]
titles=[]
years=[]

for car in cars:
    stock=car.find('span',class_='stock-label').text
    stock=stock.split(':')[1]
    stocks.append(stock)

    vin=car.span.text
    vin=vin.split(':')[1]
    vins.append(vin)

    price=car.find('div',class_='price-block our-price real-price').find('span',class_='price').text
    prices.append(price)
    prices=[x.replace('\n','').replace('\t','') for x in prices]
        
    year=car.find('a').text
    if year.split(" ")[0] == "Certified":
        year=year.split(" ")[2]
        years.append(year)
    else:
        year=year.split(" ")[1]
        years.append(year)
        
    title=car.find('a').text
    if title.split(' ',2)[0]=='Pre-Owned':
        title=title.split(' ',2)[2]
        titles.append(title)
    else:
        title=title.split(' ',3)[3]
        titles.append(title)

In [248]:
stockton_df_3=pd.DataFrame({'Stock #': stocks,
'Original Price': prices,
'Vin #': vins,
'Vehicle Name':titles,
'Year':years
})
stockton_df_3

,Stock #,Original Price,Vin #,Vehicle Name,Year
0,P3401,"$32,988",1C6SRFBT4KN667627,Ram 1500 Big Horn/Lone Star 4WD,2019
1,P3427,"$32,988",1FTEW1EG3JKE48321,Ford F-150 XLT 4WD,2018
2,P3443,"$34,488",WDC0G4KB2HF123075,Mercedes-Benz GLC 300 AWD 4MATIC®,2017
3,5568A,"$34,988",WDDZF4JB3HA028724,Mercedes-Benz E 300,2017
4,P3459,"$35,988",4JGDA5JB9GA790135,Mercedes-Benz GLE 350,2016
5,P3417,"$36,988",1GYKNFRS0KZ130547,Cadillac XT5 Premium Luxury AWD AWD,2019
6,P3418,"$37,988",JN8AY2NC4KX509731,Nissan Armada SL With Navigation & AWD,2019
7,P3458,"$37,999",4JGDA5HB1GA724944,Mercedes-Benz GLE 350 AWD 4MATIC®,2016
8,L5003,"$38,499",55SWF4JB0JU271349,Mercedes-Benz C 300,2018
9,5710A,"$39,988",WDDZF4JB0JA342143,Mercedes-Benz E 300,2018
10,P3454,"$39,999",1GNSKHKC2JR334737,Chevrolet Suburban LT 4WD,2018
11,P3360,"$39,999",WDC0G4KB3JV036510,Mercedes-Benz GLC 300 AWD 4MATIC®,2018
12,P3438,"$41,988",WDC0J4KB3HF189782,Mercedes-Benz GLC 300 AWD 4MATIC®,2017
13,P3402,"$42,988",1GNSKBKC7KR121703,Chevrolet Tahoe LT 4WD,2019
14,L5335,"$43,995",55SWF8DB4KU285193,Mercedes-Benz C 300,2019
15,L5473,"$44,375",55SWF8DB5KU298714,Mercedes-Benz C 300,2019
16,P3455,"$44,988",1FT7W2BT6JEB91007,Ford Super Duty F-250 SRW XLT 4WD,2018
17,L5260,"$46,835",WDC0G4JB0KV122800,Mercedes-Benz GLC 300,2019
18,P3315,"$53,988",WDDJK6FA4GF039835,Mercedes-Benz SL 400,2016
19,L5366,"$60,555",WDDZF4JB3KA552267,Mercedes-Benz E 300,2019

In [249]:
stockton_df_3=pd.merge(stockton_df_3,options_df,left_index=True,right_index=True)
stockton_df_3

,Stock #,Original Price,Vin #,Vehicle Name,Year,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,P3401,"$32,988",1C6SRFBT4KN667627,Ram 1500 Big Horn/Lone Star 4WD,2019,4WD,Regular Unleaded V-8 5.7 L/345,Billet Silver Metallic Clearcoat,21 MPG ...,Black,"24,283",8-Speed Automatic w/OD
1,P3427,"$32,988",1FTEW1EG3JKE48321,Ford F-150 XLT 4WD,2018,4WD,Twin Turbo Regular Unleaded V-6 3.5 L/213,Ingot Silver Metallic,23 MPG ...,Medium Earth Gray,"18,677",NaN
2,P3443,"$34,488",WDC0G4KB2HF123075,Mercedes-Benz GLC 300 AWD 4MATIC®,2017,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Polar White,28 MPG ...,Black MB-Tex,"22,395",9-Speed Automatic w/OD
3,5568A,"$34,988",WDDZF4JB3HA028724,Mercedes-Benz E 300,2017,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,White,30 MPG ...,NaN,"45,051",9-Speed Automatic w/OD
4,P3459,"$35,988",4JGDA5JB9GA790135,Mercedes-Benz GLE 350,2016,RWD,Premium Unleaded V-6 3.5 L/213,NaN,24 MPG ...,NaN,"27,888",7-Speed Automatic w/OD
5,P3417,"$36,988",1GYKNFRS0KZ130547,Cadillac XT5 Premium Luxury AWD AWD,2019,AWD,Gas V6 3.6L/222,Radiant Silver Metallic,25 MPG ...,Sahara Beige,"26,053",8-Speed Automatic
6,P3418,"$37,988",JN8AY2NC4KX509731,Nissan Armada SL With Navigation & AWD,2019,AWD,Regular Unleaded V-8 5.6 L/339,Super Black,18 MPG ...,Charcoal,"22,691",7-Speed Automatic w/OD
7,P3458,"$37,999",4JGDA5HB1GA724944,Mercedes-Benz GLE 350 AWD 4MATIC®,2016,AWD 4MATIC,Premium Unleaded V-6 3.5 L/213,NaN,22 MPG ...,NaN,"21,531",7-Speed Automatic w/OD
8,L5003,"$38,499",55SWF4JB0JU271349,Mercedes-Benz C 300,2018,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Lunar Blue Metallic,33 MPG ...,Silk Beige MB-Tex,"7,081",9-Speed Automatic w/OD
9,5710A,"$39,988",WDDZF4JB0JA342143,Mercedes-Benz E 300,2018,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Polar White,30 MPG ...,Black MB-Tex,"31,167",9-Speed Automatic w/OD
10,P3454,"$39,999",1GNSKHKC2JR334737,Chevrolet Suburban LT 4WD,2018,4WD,Gas/Ethanol V8 5.3L/,Black,22 MPG ...,Jet Black,"38,892",6-Speed Automatic
11,P3360,"$39,999",WDC0G4KB3JV036510,Mercedes-Benz GLC 300 AWD 4MATIC®,2018,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Black,28 MPG ...,Black MB-Tex,"6,305",9-Speed Automatic w/OD
12,P3438,"$41,988",WDC0J4KB3HF189782,Mercedes-Benz GLC 300 AWD 4MATIC®,2017,AWD 4MATIC,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Polar White,27 MPG ...,Black MB-Tex,"29,640",9-Speed Automatic w/OD
13,P3402,"$42,988",1GNSKBKC7KR121703,Chevrolet Tahoe LT 4WD,2019,4WD,Gas/Ethanol V8 5.3L/,Silver Ice Metallic,21 MPG ...,Cocoa/Dune,"20,366",6-Speed Automatic
14,L5335,"$43,995",55SWF8DB4KU285193,Mercedes-Benz C 300,2019,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,designo Cardinal Red Metallic,34 MPG ...,Silk Beige MB-Tex,"7,839",9-Speed Automatic w/OD
15,L5473,"$44,375",55SWF8DB5KU298714,Mercedes-Benz C 300,2019,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Black,34 MPG ...,Black MB-Tex,"12,663",9-Speed Automatic w/OD
16,P3455,"$44,988",1FT7W2BT6JEB91007,Ford Super Duty F-250 SRW XLT 4WD,2018,4WD,Intercooled Turbo Diesel V-8 6.7 L/406,Ingot Silver Metallic,MPG ...,Black,"36,022",6-Speed Automatic w/OD
17,L5260,"$46,835",WDC0G4JB0KV122800,Mercedes-Benz GLC 300,2019,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Mojave Silver Metallic,27 MPG ...,Black MB-Tex,"7,628",9-Speed Automatic w/OD
18,P3315,"$53,988",WDDJK6FA4GF039835,Mercedes-Benz SL 400,2016,RWD,Twin Turbo Premium Unleaded V-6 3.0 L/183,designo Cardinal Red,27 MPG ...,Porcelain / Black Nappa Leather,"28,287",7-Speed Automatic w/OD
19,L5366,"$60,555",WDDZF4JB3KA552267,Mercedes-Benz E 300,2019,RWD,Intercooled Turbo Premium Unleaded I-4 2.0 L/121,Black,30 MPG ...,Black MB-Tex,0,9-Speed Automatic w/OD

In [250]:
stockton_df=pd.concat([stockton_df_1,stockton_df_2,stockton_df_3])
stockton_df.head()

,Stock #,Original Price,Vin #,Vehicle Name,Year,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans
0,P3392A,"$8,900",JTHBK262X75028035,Lexus IS 250 250,2007,RWD,Gas V6 2.5L/152,Charcoal,32 MPG ...,NaN,"157,858",6-Speed Automatic
1,L5328A,"$9,999",WDBUF65J85A693548,Mercedes-Benz E-Class 3.2L,2005,RWD,Gas V6 3.2L/195,Capri Blue Metallic,28 MPG ...,NaN,"74,456",5-Speed Automatic w/OD
2,P3423A,"$11,040",1GCVKREC5EZ410142,Chevrolet Silverado 1500 LT 4WD,2014,FWD,Regular Unleaded I-4 1.6 L/97,Chalk White,36 MPG ...,Beige,"24,026",6-Speed Automatic w/OD
3,P3440,"$11,988",KMHCT4AE5HU362511,Hyundai Accent SE,2017,RWD,Turbocharged Gas I4 1.8L/110,Arctic White,31 MPG ...,Almond MB-Tex,"136,268",7-Speed Automatic
4,P3349A,"$11,995",WDDGF4HB6CA728789,Mercedes-Benz C 250 With Navigation,2012,FWD,Regular Unleaded I-4 1.8 L/110,Super Black,37 MPG ...,Charcoal,"23,821",1-Speed CVT w/OD

In [251]:
location=stockton_soup_1.find('h1').text
location=location.split('in ',1)[1]

In [252]:
stockton_df['Location']=location

In [253]:
stockton_df.head()

,Stock #,Original Price,Vin #,Vehicle Name,Year,Drivetrain,Engine,Exterior,HWY,Interior,Mileage,Trans,Location
0,P3392A,"$8,900",JTHBK262X75028035,Lexus IS 250 250,2007,RWD,Gas V6 2.5L/152,Charcoal,32 MPG ...,NaN,"157,858",6-Speed Automatic,"Stockton, CA"
1,L5328A,"$9,999",WDBUF65J85A693548,Mercedes-Benz E-Class 3.2L,2005,RWD,Gas V6 3.2L/195,Capri Blue Metallic,28 MPG ...,NaN,"74,456",5-Speed Automatic w/OD,"Stockton, CA"
2,P3423A,"$11,040",1GCVKREC5EZ410142,Chevrolet Silverado 1500 LT 4WD,2014,FWD,Regular Unleaded I-4 1.6 L/97,Chalk White,36 MPG ...,Beige,"24,026",6-Speed Automatic w/OD,"Stockton, CA"
3,P3440,"$11,988",KMHCT4AE5HU362511,Hyundai Accent SE,2017,RWD,Turbocharged Gas I4 1.8L/110,Arctic White,31 MPG ...,Almond MB-Tex,"136,268",7-Speed Automatic,"Stockton, CA"
4,P3349A,"$11,995",WDDGF4HB6CA728789,Mercedes-Benz C 250 With Navigation,2012,FWD,Regular Unleaded I-4 1.8 L/110,Super Black,37 MPG ...,Charcoal,"23,821",1-Speed CVT w/OD,"Stockton, CA"

In [254]:
stockton_df.to_csv('stockton_df.csv', sep = ',')